# Generated by Django 4.2.2 on 2023-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop_projects", "0007_alter_category_options_alter_project_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Archived"), (1, "Available")], default=1
            ),
            preserve_default=False,
        ),
    ]
