# Generated by Django 4.2.2 on 2023-06-30 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop_projects", "0011_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="shop_projects.creator",
            ),
        ),
    ]
