# Generated by Django 4.2.2 on 2023-07-06 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_projects', '0013_alter_project_category_alter_project_creator_donat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archived'), (1, 'Available')], default=1),
        ),
    ]
