# Generated by Django 4.2.2 on 2023-07-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_projects', '0014_alter_category_options_category_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='status',
            field=models.IntegerField(choices=[(0, 'Archived'), (1, 'Available')], default=1),
        ),
    ]
