# Generated by Django 4.2.2 on 2023-07-06 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_projects', '0017_alter_project_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creator',
            options={'verbose_name_plural': 'creators'},
        ),
        migrations.AlterModelOptions(
            name='donat',
            options={'verbose_name_plural': 'donats'},
        ),
    ]
