# Generated by Django 4.2.2 on 2023-07-08 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_projects', '0020_orderpaymentdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'orders'},
        ),
    ]
