# Generated by Django 4.2.2 on 2023-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0002_imagecarnumdetect'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoExerciseRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('VideoField', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
