# Generated by Django 4.2.2 on 2023-07-20 18:35

from django.db import migrations, models
import my_projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0003_videoexerciserec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videoexerciserec',
            name='VideoField',
            field=models.FileField(null=True, upload_to='videos/', validators=[my_projects.validators.validate_max_video_size], verbose_name=''),
        ),
    ]
