# Generated by Django 4.2.2 on 2023-07-30 11:20

from django.db import migrations, models
import my_projects.validators


class Migration(migrations.Migration):

    dependencies = [
        ('my_projects', '0006_alter_videoexerciserec_inputvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecarnumdetect',
            name='InputImage',
            field=models.ImageField(upload_to='images/', validators=[my_projects.validators.validate_max_image_size]),
        ),
        migrations.AlterField(
            model_name='imagesexagedetect',
            name='InputImage',
            field=models.ImageField(upload_to='images/', validators=[my_projects.validators.validate_max_image_size]),
        ),
    ]
